= CalConnect Standard: Enhanced Synchronization for Calendaring Extensions to WebDAV (CalDAV)

This work item belongs to CalConnect (TCs).

image:https://github.com/CalConnect/cc-caldav-sync/workflows/generate/badge.svg["Build Status", link="https://github.com/CalConnect/cc-caldav-sync/actions?workflow=generate"]

This document is available in its rendered forms here:

* https://calconnect.github.io/cc-caldav-sync/[CalConnect: Enhanced Synchronization for CalDAV (HTML)]

== General

This document defines new protocol features for CalDAV (RFC 4791) to improve the efficiency of synchronizing data changes between a client and server.

The document is published as the following:

* CalConnect CC 51012
* IETF draft-daboo-caldav-sync-00


== Fetching the document

[source,sh]
----
git clone https://github.com/CalConnect/cc-caldav-sync/
----


== Installing build tools

See https://www.metanorma.com/author/topics/install/


== Running via Docker or locally

If you have installed the build tools locally, and wish to run the
locally-installed compilation tools, there is nothing further to set.

If you don't want to deal with local dependencies, use the docker:

[source,sh]
----
docker run -v "$(pwd)":/metanorma -w /metanorma -it metanorma/mn metanorma site generate --agree-to-terms
----


== Building the document

[source,sh]
----
metanorma site generate --agree-to-terms
----

The generated documents are accessible under `_site/`.


== Iterating the document

[source,sh]
----
metanorma site generate --agree-to-terms
open _site/index.html
----


== License

Copyright its respective authors and CalConnect.
